# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 540724caa1627f56955ca7426ecac62bf74002f39e0363fa232c1d7120517ecaecdc61f70157c0d9b60fbf41092208f877ce7bbb66435829df21efbf4dda164b

test:
  secret_key_base: 17a202fcd23d82ce2ba85f85e63c19a2f42128c532e1a4c999b62eba1366887d649b51caf4399ab68d98cf841369388ba94443841821a7e1f53c4872269b8edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
